version: '3.9'
services:
  docserver:
    image: onlyoffice/4testing-documentserver-de:${DOCSERVER_VERSION}
    ports:
      - "6060:80"
    volumes:
      - ${PATH_TO_PLUGINS}:/var/www/onlyoffice/documentserver/sdkjs-plugins/plugins
  nginx:
    image: nginx:plugins
    ports:
      - "6061:80"
    volumes:
      - ./:/usr/share/nginx/html/
