version: '3.9'
services:
  docserver:
    image: onlyoffice/4testing-documentserver-ee:latest
    ports:
      - "6060:80"
    volumes:
      - /home/maxim/Main_project/starter_sdkjsplugins/plugins_list:/var/www/onlyoffice/documentserver/sdkjs-plugins/plugins
  nginx:
    image: nginx:plugins
    ports:
      - "6061:80"
    volumes:
      - ./:/usr/share/nginx/html/
