version: '3.9'
services:
  docserver:
    image: onlyoffice/4testing-documentserver-ee:${DOCSERVER_VERSION}
    volumes:
      - ${LOG}/logs:/var/log/onlyoffice
      - ${LOG}/data:/var/www/onlyoffice/Data
      - ${LOG}/lib:/var/lib/onlyoffice
      - ${LOG}/db:/var/lib/postgresql
    ports:
      - "6060:80"
